version: '3'
services:
  web:
    image: 2.3-slim-jessie
    build: .
    entrypoint: /customers-service/docker-entrypoint.sh
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
    - .:/customers-service
    ports:
    - "3000:3000"